### ISSUE TITLE
Error while using cordova.plugins.SecureKeyStore.get for the key that doesn't exist.

### ISSUE THREAD

**Issue by vaibhav915** [pradeep1991singh/cordova-plugin-secure-key-store#10]
Hi,
I am getting error while using get method for the key that doesnot exist in keystore.
       cordova.plugins.SecureKeyStore.get(function (res) {
         alert(res);
       }, function (error) {
          alert(error);
       }, "abc");

ERROR MESSAGE:
Api-level:21
Exception: Need RSA private or public key

Can I get some error code that state key doesn't exist instead of above message

**Comment by pradeep1991singh** [comment]
@vaibhav915 added in v1.5.2
