### ISSUE TITLE
Getting "mutating method sent to immutable object" error

### ISSUE THREAD

**Issue by okonon** [pradeep1991singh/cordova-plugin-secure-key-store#11]
Freshly installed app throws following error when attempting to store value for key first time:

```
 {"code":9,"message":"error saving key, please try to un-install and re-install app again","actual-error":-[__NSCFDictionary setObject:forKey:]: mutating method sent to immutable object}
```

Reinstalling the app does not help.

@pradeep1991singh any suggestions how to resolve it?

**Comment by pradeep1991singh** [comment]
@okonon device details?

**Comment by okonon** [comment]
iPhone 7+ running iOS 10.3.1

**Comment by okonon** [comment]
@pradeep1991singh

**Comment by pradeep1991singh** [comment]
@okonon I just tested it on iPhone 7+ and its working fine. let me know the steps you followed with the fresh installation and other details if any.

**Comment by okonon** [comment]
Switched to another plugin due to support of secure storage that I needed as well.
