### ISSUE TITLE
1.5.5

### ISSUE THREAD

**Issue by neptsoft** [pradeep1991singh/cordova-plugin-secure-key-store#13]
Dear Pradeep, first and most important:  thank you very much for such a great plugin.
Are you planning to push version 1.5.5  (latest fix for ios keys) to NPM ?

Thanks again, kind regards,
Julian

**Comment by pradeep1991singh** [comment]
@neptsoft Its already there, let me know if you are seeing it.

**Comment by neptsoft** [comment]
It is there :)  thank you very much !
