### ISSUE TITLE
input must be under 256 bytes

### ISSUE THREAD

**Issue by simonhaenisch** [pradeep1991singh/cordova-plugin-secure-key-store#14]
I'm trying to store a JWT on Android and get the following error message:

```json
{ "code": 9, "api-level": 22, "message": "input must be under 256 bytes" }
```

Is there any way to get around this limit?

**Comment by pradeep1991singh** [comment]
You car break token in multiple chunks for 256 and whenever needed can get and combine them in one.

**Comment by simonhaenisch** [comment]
I just read that the 256 bytes limit is because of RSA encryption... with AES there is no limit. However it's only supported by API level 23 (see [here](https://developer.android.com/training/articles/keystore#SupportedAlgorithms)) and I'm on 22. Just leaving this note here in case someone else runs into it in the future.

Will have to find another way to store the token (breaking into chunks is too complex for this task imo).
