### ISSUE TITLE
Exception: java.security.NoSuchAlgorithmException

### ISSUE THREAD

**Issue by nishammahsin** [pradeep1991singh/cordova-plugin-secure-key-store#6]
Exception: java.security.NoSuchAlgorithmException: KeyStore AndroidOpenSSL implementation not found
getting this error

**Comment by pradeep1991singh** [comment]
Hi @nishammahsin I was also able to reproduce this issue on api level 19 and I have pushed fixes in latest release which is v1.4.1. Get latest release, hope it should fix issue for you.
Thanks.

**Comment by nishammahsin** [comment]
Thanks. it fixed
