### ISSUE TITLE
I found one more issue in iOS

### ISSUE THREAD

**Issue by Krishna25Vrinsoft** [pradeep1991singh/cordova-plugin-secure-key-store#9]
Hello pradeepsingh,

I found one more issue in iOS. where i installed app and stored some id then i did uninstalled app in my device then again i installed my device on that time i got all stored value again. it should be clear from storage.
Can you plz resolve it?

Let me know if you need any more clarification

Thanks you

**Comment by Krishna25Vrinsoft** [comment]
Have you got any solution?

**Comment by pradeep1991singh** [comment]
@Krishna25Vrinsoft Try latest code available at `master` branch.

**Comment by pradeep1991singh** [comment]
@Krishna25Vrinsoft  did u tried new updates?

**Comment by pradeep1991singh** [comment]
Fixed in v1.5.1
